=== Errmi/XML-Projects/voyageur de santé/DATA/xsd/cabinetInfirmier.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
           xmlns="http://www.ujf-grenoble.fr/l3miage/medical"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="soinsGrenoble" type="Cabinet"/>

    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" type="NomRueVilleString"/>
            <xs:element name="adresse" type="Adresse"/>
            <xs:element name="infirmiers" type="Infirmiers"/>
            <xs:element name="patients" type="Patients" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence> 
    </xs:complexType>

    <!--Restricting names and road addresses (should restrict length as well?)-->
    <xs:simpleType name="NomRueVilleString">
        <xs:restriction base="xs:string">
            <xs:pattern value="/^[ a-zA-ZÀ-ÿ\u00f1\u00d1]*$/g"/> <!--Matches letters, accents and spaces except from spaces at beginning-->
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Adresse">
        <xs:sequence>
            <xs:element name="étage" type="ÉtageInt" minOccurs="0" maxOccurs="1"/>
            <xs:element name="numéro" type="xs:int" minOccurs="0" maxOccurs="1"/>
            <xs:element name="rue" type="NomEtRueString"/>
            <xs:element name="codePostal" type="CodePostalString"/>
            <xs:element name="ville" type="NomRueVilleString"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="ÉtageInt">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CodePostalString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Infirmiers">
        <xs:sequence>
            <xs:element name="infirmier" type="Infirmier" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Infirmier">
        <xs:complexContent>
            <xs:extension base="Personne">
                <xs:sequence>
                    <xs:element name="photo" type="PhotoString" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attribute name="id" type="IdInfirmierOuActe" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="PhotoString">
        <xs:restriction base="xs:string">
            <xs:pattern value="([^\\s]+(\\.(?i)(jpe?g|png|gif|bmp))$)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IdInfirmierOuActe">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" type="Patient" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Patient">
        <xs:complexContent>
            <xs:extension base="Personne">
                <xs:sequence>
                    <xs:element name="sexe" type="Sexe"/>
                    <xs:element name="naissance" type="NaissanceDate"/>
                    <xs:element name="numéro" type="NrSécuritéSociale"/>
                    <xs:element name="adresse" type="Adresse"/>
                    <xs:element name="visite" type="Visite" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="F"/>
            <xs:enumeration value="H"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NaissanceDate">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="1885-01-01"/>
            <xs:minInclusive value="2015-12-07"/> <!--Current date, would have to be updated every day...-->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NrSécuritéSociale">
        <xs:restriction base="xs:string">
            <xs:pattern value="/
            [12][0-9]{2}(0[1-9]|1[0-2])(2[AB]|[0-9]{2})[0-9]{3}[0-9]{3}([0-9]{2})
            /"/>
        </xs:restriction>
    </xs:simpleType>
    

    <xs:complexType name="Personne">
        <xs:sequence>
            <xs:element name="nom" type="NomRueVilleString"/>
            <xs:element name="prénom" type="NomRueVilleString"/>   
        </xs:sequence>    
    </xs:complexType>

    <xs:complexType name="Visite">
        <xs:sequence>
            <xs:element name="acte" type="Acte"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required"/>
        <xs:attribute name="intervenant" type="IdInfirmierOuActe"/> <!--Feil? Må være eksisterende id?-->
    </xs:complexType>

    <xs:complexType name="Acte">
        <xs:attribute name="id" type="IdInfirmierOuActe" use="required"/>
    </xs:complexType>

</xs:schema>

=== Errmi/XML-Projects/Voyageur de Sante/DATA/xml/1cabinetInfirmier11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->


<ns1:soinsGrenoble
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://www.ujf-grenoble.fr/l3miage/medical'
    xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/medical file:/Users/saraengesvik/NetBeansProjects/Voyageur%20de%20Santé/DATA/xsd/cabinetInfirmier.xsd'>
    
    <ns1:nom>soins à Grenoble</ns1:nom>
    
    <ns1:adresse>
        <ns1:numéro>60</ns1:numéro>
        <ns1:rue>rue de la Chimie</ns1:rue>
        <ns1:codePostal>38041</ns1:codePostal>
        <ns1:ville>Grenoble</ns1:ville>
    </ns1:adresse>
    
    <ns1:infirmiers>
        <ns1:infirmier id="001">
            <ns1:nom>Fréchie</ns1:nom>
            <ns1:prénom>Sarah</ns1:prénom>
            <ns1:photo>sarah.png</ns1:photo>
        </ns1:infirmier>
        <ns1:infirmier id="002">
            <ns1:nom>Stické</ns1:nom>
            <ns1:prénom>Sophie</ns1:prénom>
            <ns1:photo>sophie.png</ns1:photo>
        </ns1:infirmier>
        <ns1:infirmier id="003">
            <ns1:nom>Ochon</ns1:nom>
            <ns1:prénom>Paul</ns1:prénom>
            <ns1:photo>paul.png</ns1:photo>
        </ns1:infirmier>
    </ns1:infirmiers>
    
    <ns1:patients>
        <ns1:patient>
            <ns1:nom>Alécole</ns1:nom>
            <ns1:prénom>Yvon</ns1:prénom>
            <ns1:sexe>H</ns1:sexe>
            <ns1:naissance>1998-08-22</ns1:naissance>
            <ns1:numéro>19808205545852</ns1:numéro>
            <ns1:adresse>
                <ns1:étage>6</ns1:étage>
                <ns1:numéro>50</ns1:numéro>
                <ns1:rue>Avenue Félix Viallet</ns1:rue>
                <ns1:codePostal>38031</ns1:codePostal>
                <ns1:ville>Grenoble</ns1:ville>
            </ns1:adresse>
            <ns1:visite date="2015-12-08" intervenant="001">
                <ns1:acte id="109"></ns1:acte>
            </ns1:visite>
        </ns1:patient>
        <ns1:patient>
            <ns1:nom>Orouge</ns1:nom>
            <ns1:prénom>Elvire</ns1:prénom>
            <ns1:sexe>F</ns1:sexe>
            <ns1:naissance>1982-03-08</ns1:naissance>
            <ns1:numéro>2820323069052</ns1:numéro>
            <ns1:adresse>
                <ns1:rue>Rond-Point de la Croix de Vie</ns1:rue>
                <ns1:codePostal>38700</ns1:codePostal>
                <ns1:ville>La Tronche</ns1:ville>
            </ns1:adresse>
            <ns1:visite date="2015-12-08">
                <ns1:acte id="300"></ns1:acte>
            </ns1:visite>
        </ns1:patient>
        <ns1:patient>
            <ns1:nom>Pien</ns1:nom>
            <ns1:prénom>Oscare</ns1:prénom>
            <ns1:sexe>F</ns1:sexe>
            <ns1:naissance>1975-08-25</ns1:naissance>
            <ns1:numéro>1750373065692</ns1:numéro>
            <ns1:adresse>
                <ns1:rue>rue Casimir Brenier</ns1:rue>
                <ns1:codePostal>38000</ns1:codePostal>
                <ns1:ville>Grenoble</ns1:ville>
            </ns1:adresse>
            <ns1:visite date="2015-12-08">
                <ns1:acte id="101"></ns1:acte>
                <ns1:acte id="104"></ns1:acte>
            </ns1:visite>
        </ns1:patient>
        <ns1:patient>
            <ns1:nom>Kapoëtla</ns1:nom>
            <ns1:prénom>Xavier</ns1:prénom>
            <ns1:sexe>H</ns1:sexe>
            <ns1:naissance>2011-08-02</ns1:naissance>
            <ns1:numéro>1110833063035</ns1:numéro>
            <ns1:adresse>
                <ns1:numéro>25</ns1:numéro>
                <ns1:rue>rue des Martyrs</ns1:rue>
                <ns1:codePostal>38042</ns1:codePostal>
                <ns1:ville>Grenoble</ns1:ville>
            </ns1:adresse>
            <ns1:visite date="2015-12-08">
                <ns1:acte id="111"></ns1:acte>
            </ns1:visite>
        </ns1:patient>
    </ns1:patients>
</ns1:soinsGrenoble>
