=== Errmi/XML-Projects/TUX/DATA/xsd/dico.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
            targetNamespace="http://www.univ-grenoble.fr/dico"
            xmlns="http://www.univ-grenoble.fr/dico"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    
   <xs:element name="dico" type="Dictionnaire"/>
<xs:complexType name="Dictionnaire">
        <xs:sequence>
            <xs:element name="mot" type="Mot" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

<xs:complexType name="Mot">
    <xs:simpleContent>
        <xs:extension base="StringMot">
            <xs:attribute name="niveau" type="IntNiveau"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

    <xs:simpleType name="StringMot">
        <xs:restriction base="xs:string">
            <xs:pattern value="^[a-zA-Z_\-]*$"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IntNiveau">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Errmi/XML-Projects/TUX/src/xml/dico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<ns1:dico
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://myGame/tux'
    xsi:schemaLocation='http://myGame/tux ../xsd/dico.xsd'>
    
        <ns1:mot niveau="1">mot</ns1:mot>
        <ns1:mot niveau="1">cle</ns1:mot>
        <ns1:mot niveau="2">indice</ns1:mot>
        <ns1:mot niveau="2">fermer</ns1:mot>
        <ns1:mot niveau="3">parallèle</ns1:mot>
        <ns1:mot niveau="4">méditerranée</ns1:mot>
        <ns1:mot niveau="5">kinésithérapeute</ns1:mot>

</ns1:dico>
